version: '3'
services: 
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    env_file: ./mysql/.env
    restart: always
    environment: 
      TZ: "Asia/Tokyo"
    ports: 
      - 3306:3306
    volumes: 
      - db-volume:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - db

volumes: 
  db-volume:
